// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const _ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
const _ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt int64  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *User) Reset()         { *x = User{}; if protoimpl.UnsafeEnabled { mi := &file_users_proto_msgTypes[0]; ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x)); ms.StoreMessageInfo(mi) } }
func (x *User) String() string { return protoimpl.X.MessageStringOf(x) }
func (*User) ProtoMessage()    {}
func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*User) Descriptor() ([]byte, []int) { return file_users_proto_rawDescGZIP(), []int{0} }
func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}
func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type UserURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Url           string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	NormalizedUrl string `protobuf:"bytes,4,opt,name=normalized_url,json=normalizedUrl,proto3" json:"normalized_url,omitempty"`
	PollingIntervalSeconds int32 `protobuf:"varint,5,opt,name=polling_interval_seconds,json=pollingIntervalSeconds,proto3" json:"polling_interval_seconds,omitempty"`
	CreatedAt     int64  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *UserURL) Reset()         { *x = UserURL{}; if protoimpl.UnsafeEnabled { mi := &file_users_proto_msgTypes[1]; ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x)); ms.StoreMessageInfo(mi) } }
func (x *UserURL) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UserURL) ProtoMessage()    {}
func (x *UserURL) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*UserURL) Descriptor() ([]byte, []int) { return file_users_proto_rawDescGZIP(), []int{1} }
func (x *UserURL) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *UserURL) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}
func (x *UserURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}
func (x *UserURL) GetNormalizedUrl() string {
	if x != nil {
		return x.NormalizedUrl
	}
	return ""
}
func (x *UserURL) GetPollingIntervalSeconds() int32 {
	if x != nil {
		return x.PollingIntervalSeconds
	}
	return 0
}
func (x *UserURL) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateUserRequest) Reset()         { *x = CreateUserRequest{}; if protoimpl.UnsafeEnabled { mi := &file_users_proto_msgTypes[2]; ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x)); ms.StoreMessageInfo(mi) } }
func (x *CreateUserRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CreateUserRequest) ProtoMessage()    {}
func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return file_users_proto_rawDescGZIP(), []int{2} }
func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}
func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *CreateUserResponse) Reset()         { *x = CreateUserResponse{}; if protoimpl.UnsafeEnabled { mi := &file_users_proto_msgTypes[3]; ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x)); ms.StoreMessageInfo(mi) } }
func (x *CreateUserResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CreateUserResponse) ProtoMessage()    {}
func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*CreateUserResponse) Descriptor() ([]byte, []int) { return file_users_proto_rawDescGZIP(), []int{3} }
func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserRequest) Reset()         { *x = GetUserRequest{}; if protoimpl.UnsafeEnabled { mi := &file_users_proto_msgTypes[4]; ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x)); ms.StoreMessageInfo(mi) } }
func (x *GetUserRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetUserRequest) ProtoMessage()    {}
func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return file_users_proto_rawDescGZIP(), []int{4} }
func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetUserResponse) Reset()         { *x = GetUserResponse{}; if protoimpl.UnsafeEnabled { mi := &file_users_proto_msgTypes[5]; ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x)); ms.StoreMessageInfo(mi) } }
func (x *GetUserResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetUserResponse) ProtoMessage()    {}
func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return file_users_proto_rawDescGZIP(), []int{5} }
func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type AddUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Url    string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	PollingIntervalSeconds int32 `protobuf:"varint,3,opt,name=polling_interval_seconds,json=pollingIntervalSeconds,proto3" json:"polling_interval_seconds,omitempty"`
}

func (x *AddUrlRequest) Reset()         { *x = AddUrlRequest{}; if protoimpl.UnsafeEnabled { mi := &file_users_proto_msgTypes[6]; ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x)); ms.StoreMessageInfo(mi) } }
func (x *AddUrlRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*AddUrlRequest) ProtoMessage()    {}
func (x *AddUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*AddUrlRequest) Descriptor() ([]byte, []int) { return file_users_proto_rawDescGZIP(), []int{6} }
func (x *AddUrlRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}
func (x *AddUrlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}
func (x *AddUrlRequest) GetPollingIntervalSeconds() int32 {
	if x != nil {
		return x.PollingIntervalSeconds
	}
	return 0
}

type AddUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url *UserURL `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *AddUrlResponse) Reset()         { *x = AddUrlResponse{}; if protoimpl.UnsafeEnabled { mi := &file_users_proto_msgTypes[7]; ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x)); ms.StoreMessageInfo(mi) } }
func (x *AddUrlResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*AddUrlResponse) ProtoMessage()    {}
func (x *AddUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*AddUrlResponse) Descriptor() ([]byte, []int) { return file_users_proto_rawDescGZIP(), []int{7} }
func (x *AddUrlResponse) GetUrl() *UserURL {
	if x != nil {
		return x.Url
	}
	return nil
}

type ListUrlsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit  int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListUrlsRequest) Reset()         { *x = ListUrlsRequest{}; if protoimpl.UnsafeEnabled { mi := &file_users_proto_msgTypes[8]; ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x)); ms.StoreMessageInfo(mi) } }
func (x *ListUrlsRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListUrlsRequest) ProtoMessage()    {}
func (x *ListUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*ListUrlsRequest) Descriptor() ([]byte, []int) { return file_users_proto_rawDescGZIP(), []int{8} }
func (x *ListUrlsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}
func (x *ListUrlsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListUrlsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []*UserURL `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *ListUrlsResponse) Reset()         { *x = ListUrlsResponse{}; if protoimpl.UnsafeEnabled { mi := &file_users_proto_msgTypes[9]; ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x)); ms.StoreMessageInfo(mi) } }
func (x *ListUrlsResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListUrlsResponse) ProtoMessage()    {}
func (x *ListUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*ListUrlsResponse) Descriptor() ([]byte, []int) { return file_users_proto_rawDescGZIP(), []int{9} }
func (x *ListUrlsResponse) GetUrls() []*UserURL {
	if x != nil {
		return x.Urls
	}
	return nil
}

var File_users_proto protoreflect.FileDescriptor

var file_users_proto_rawDesc = []byte{0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f}

var (
	file_users_proto_rawDescOnce sync.Once
	file_users_proto_rawDescData = file_users_proto_rawDesc
)

func file_users_proto_rawDescGZIP() []byte {
	file_users_proto_rawDescOnce.Do(func() {
		file_users_proto_rawDescData = protoimpl.X.CompressGZIP(file_users_proto_rawDescData)
	})
	return file_users_proto_rawDescData
}

var file_users_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_users_proto_goTypes = []interface{}{
	(*User)(nil),
	(*UserURL)(nil),
	(*CreateUserRequest)(nil),
	(*CreateUserResponse)(nil),
	(*GetUserRequest)(nil),
	(*GetUserResponse)(nil),
	(*AddUrlRequest)(nil),
	(*AddUrlResponse)(nil),
	(*ListUrlsRequest)(nil),
	(*ListUrlsResponse)(nil),
}
var file_users_proto_depIdxs = []int32{}

func init() { file_users_proto_init() }
func file_users_proto_init() {
	if File_users_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_users_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUrlsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUrlsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_users_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_proto_goTypes,
		DependencyIndexes: file_users_proto_depIdxs,
		MessageInfos:      file_users_proto_msgTypes,
	}.Build()
	File_users_proto = out.File
	file_users_proto_rawDesc = nil
	file_users_proto_goTypes = nil
	file_users_proto_depIdxs = nil
}
